# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

env:
  TOKEN: ${{ secrets.TOKEN }}
  URI: ${{ secrets.URI }}
  RAYGUN_TOKEN: ${{ secrets.RAYGUN_TOKEN }}
  RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
  UBI_MAIL: ${{ secrets.UBI_MAIL }}
  UBI_PASSWORD: ${{ secrets.UBI_PASSWORD }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        fetch-depth: 0
        
    - name: Install Node dependencies
      run: npm i
    
    - name: Run unit and integration tests
      run: npm test
    
    - name: SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
